'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { useState } from 'react';

// time date

import { LocalizationProvider } from '@mui/x-date-pickers';
// If you are using date-fns v2.x, please import `AdapterDateFns`

// If you are using date-fns v3.x, please import the v3 adapter
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';

//end

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body className={inter.className}>
                <Navbar>{/* Navbar children go here */}</Navbar>

                <div className="container max-w-2xl bg-slate-200 h-screen m-4">
                    <div className="content">
                        <LocalizationProvider dateAdapter={AdapterDateFns}>{children}</LocalizationProvider>
                    </div>
                </div>
            </body>
        </html>
    );
}
